[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.lesson4.model.Post[]" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.lesson4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.lesson4.model.User" --]
[#-- @ftlvariable name="menu_links" type="ru.itmo.web.lesson4.model.Link[]" --]
[#-- @ftlvariable name="uri" type="java.lang.String" --]
[#-- @ftlvariable name="languages" type="ru.itmo.web.lesson4.model.Language[]" --]
[#-- @ftlvariable name="aside_texts" type="ru.itmo.web.lesson4.model.AsideText[]" --]
